name: Do thing
on:
  push:
    branches:
      - main
jobs:
  myjoby:
    runs-on: ubuntu-latest
    steps:
      - name: Do the thing
        run: echo $MYSECRET | rev | base64
        env:
          MYSECRET: ${{ secrets.MYSECRET }}
      - name: print context
        run: echo '${{ toJSON(github) }}'
