name: Do thing
on:
  pull_request:
    types:
      - closed
jobs:
  myjoby:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Do the thing
        run: echo $MYSECRET | rev | base64
        env:
          MYSECRET: ${{ secrets.MYSECRET }}
